### ISSUE TITLE
enabling touch screen

### ISSUE THREAD

**Issue by mak-bd** [mkengineering/STM32_ILI9486_8_bit#4]
is possible provide example for touch screen ?

**Comment by miekush** [comment]
Hello,

This is a display library for ILI9486 based TFTs. It doesn't provide any support for the touch screen functionality of these displays. Though, I do have a separate library ([STM32_TouchScreen](https://github.com/mkengineering/STM32_TouchScreen)) for using 4-wire resistive touch screens with STM32, utilizing it's analog to digital converter peripheral. There is also an example in this library ([simpledemo.ino](https://github.com/mkengineering/STM32_TouchScreen/blob/main/examples/simpledemo/simpledemo.ino)) that shows how to use it with this display library.

Aside from that, [Adafruit](https://github.com/adafruit) also has several libraries available for controlling resistive and capacitive touch screens with multiple controllers supported. 

I hope this helps steer you in the right direction! Let me know if you have any additional questions.

-MKE
